### ISSUE TITLE
no ferris_intent_1bpp_reverse.bmp

### ISSUE THREAD

**Issue by colossalchicken** [9names/badger2040_testing#1]
```
error: couldn't read src/../assets/ferris_intent_1bpp_reverse.bmp: No such file or directory (os error 2)
   --> src/main.rs:118:17
    |
118 |     let data2 = include_bytes!("../assets/ferris_intent_1bpp_reverse.bmp");
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `badger-test` due to previous error
```

**Comment by 9names** [comment]
I was updating this project in a hurry for a demo, forgot to add the bitmap.
I've added it, can you try again?

**Comment by 9names** [comment]
those errors are strange. can you compile other rp2040 projects?
are you trying to build in a workspace that has standard targets as well?
do you have any customisations in $CARGO_HOME/config.toml that would be messing with this project build?

**Comment by 9names** [comment]
hmm, it looks like you added `probe-run` as a dep?
don't do that. install it using `cargo install probe-run` instead.
